// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'vehicle.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$VehicleImpl _$$VehicleImplFromJson(
  Map<String, dynamic> json,
) => _$VehicleImpl(
  id: json['id'] as String,
  registration: json['registration'] as String? ?? '',
  make: json['make'] as String? ?? '',
  model: json['model'] as String? ?? '',
  year: json['year'] as String? ?? '',
  colour: json['colour'] as String? ?? '',
  fuelType: json['fuelType'] as String? ?? 'petrol',
  transmission: json['transmission'] as String? ?? '',
  vin: json['vin'] as String? ?? '',
  variant: json['variant'] as String? ?? '',
  bodyType: json['bodyType'] as String? ?? '',
  engineCC: json['engineCC'] as String? ?? '',
  engineNumber: json['engineNumber'] as String? ?? '',
  keyNumber: json['keyNumber'] as String? ?? '',
  chassisNumber: json['chassisNumber'] as String? ?? '',
  radioCode: json['radioCode'] as String? ?? '',
  description: json['description'] as String? ?? '',
  purchaseDate: json['purchaseDate'] as String? ?? '',
  purchasePrice: (json['purchasePrice'] as num?)?.toDouble() ?? 0,
  purchasedFrom: json['purchasedFrom'] as String? ?? '',
  ownership: json['ownership'] as String? ?? '',
  financeCompany: json['financeCompany'] as String? ?? '',
  agreementNumber: json['agreementNumber'] as String? ?? '',
  deposit: (json['deposit'] as num?)?.toDouble() ?? 0,
  monthlyPayment: (json['monthlyPayment'] as num?)?.toDouble() ?? 0,
  financeStartDate: json['financeStartDate'] as String? ?? '',
  financeEndDate: json['financeEndDate'] as String? ?? '',
  balloonPayment: (json['balloonPayment'] as num?)?.toDouble() ?? 0,
  annualMileageAllowance:
      (json['annualMileageAllowance'] as num?)?.toInt() ?? 0,
  numberOfPayments: (json['numberOfPayments'] as num?)?.toInt() ?? 0,
  lessor: json['lessor'] as String? ?? '',
  agreementHolder: json['agreementHolder'] as String? ?? '',
  ownershipNotes: json['ownershipNotes'] as String? ?? '',
  insurer: json['insurer'] as String? ?? '',
  insurancePolicyNumber: json['insurancePolicyNumber'] as String? ?? '',
  insuranceRenewalDate: json['insuranceRenewalDate'] as String? ?? '',
  insuranceType: json['insuranceType'] as String? ?? '',
  insuredDrivers: json['insuredDrivers'] as String? ?? '',
  insuranceAnnualCost: (json['insuranceAnnualCost'] as num?)?.toDouble() ?? 0,
  breakdownProvider: json['breakdownProvider'] as String? ?? '',
  breakdownMembershipNumber: json['breakdownMembershipNumber'] as String? ?? '',
  breakdownContact: json['breakdownContact'] as String? ?? '',
  breakdownNotes: json['breakdownNotes'] as String? ?? '',
  recoveryProvider: json['recoveryProvider'] as String? ?? '',
  recoveryArrangedVia: json['recoveryArrangedVia'] as String? ?? '',
  recoveryReference: json['recoveryReference'] as String? ?? '',
  recoveryContact: json['recoveryContact'] as String? ?? '',
  recoveryNotes: json['recoveryNotes'] as String? ?? '',
  motDueDate: json['motDueDate'] as String? ?? '',
  taxDueDate: json['taxDueDate'] as String? ?? '',
  currentMileage: (json['currentMileage'] as num?)?.toInt() ?? 0,
  notes: json['notes'] as String? ?? '',
  dvlaVerified: json['dvlaVerified'] as bool? ?? false,
  taxStatus: json['taxStatus'] as String? ?? '',
  motStatus: json['motStatus'] as String? ?? '',
  photoPath: json['photoPath'] as String? ?? '',
);

Map<String, dynamic> _$$VehicleImplToJson(_$VehicleImpl instance) =>
    <String, dynamic>{
      'id': instance.id,
      'registration': instance.registration,
      'make': instance.make,
      'model': instance.model,
      'year': instance.year,
      'colour': instance.colour,
      'fuelType': instance.fuelType,
      'transmission': instance.transmission,
      'vin': instance.vin,
      'variant': instance.variant,
      'bodyType': instance.bodyType,
      'engineCC': instance.engineCC,
      'engineNumber': instance.engineNumber,
      'keyNumber': instance.keyNumber,
      'chassisNumber': instance.chassisNumber,
      'radioCode': instance.radioCode,
      'description': instance.description,
      'purchaseDate': instance.purchaseDate,
      'purchasePrice': instance.purchasePrice,
      'purchasedFrom': instance.purchasedFrom,
      'ownership': instance.ownership,
      'financeCompany': instance.financeCompany,
      'agreementNumber': instance.agreementNumber,
      'deposit': instance.deposit,
      'monthlyPayment': instance.monthlyPayment,
      'financeStartDate': instance.financeStartDate,
      'financeEndDate': instance.financeEndDate,
      'balloonPayment': instance.balloonPayment,
      'annualMileageAllowance': instance.annualMileageAllowance,
      'numberOfPayments': instance.numberOfPayments,
      'lessor': instance.lessor,
      'agreementHolder': instance.agreementHolder,
      'ownershipNotes': instance.ownershipNotes,
      'insurer': instance.insurer,
      'insurancePolicyNumber': instance.insurancePolicyNumber,
      'insuranceRenewalDate': instance.insuranceRenewalDate,
      'insuranceType': instance.insuranceType,
      'insuredDrivers': instance.insuredDrivers,
      'insuranceAnnualCost': instance.insuranceAnnualCost,
      'breakdownProvider': instance.breakdownProvider,
      'breakdownMembershipNumber': instance.breakdownMembershipNumber,
      'breakdownContact': instance.breakdownContact,
      'breakdownNotes': instance.breakdownNotes,
      'recoveryProvider': instance.recoveryProvider,
      'recoveryArrangedVia': instance.recoveryArrangedVia,
      'recoveryReference': instance.recoveryReference,
      'recoveryContact': instance.recoveryContact,
      'recoveryNotes': instance.recoveryNotes,
      'motDueDate': instance.motDueDate,
      'taxDueDate': instance.taxDueDate,
      'currentMileage': instance.currentMileage,
      'notes': instance.notes,
      'dvlaVerified': instance.dvlaVerified,
      'taxStatus': instance.taxStatus,
      'motStatus': instance.motStatus,
      'photoPath': instance.photoPath,
    };
